os: windows
language: csharp
solution: USFM_Converter.sln
mono: none

install:
- choco install nuget.commandline
- nuget restore USFM_Converter.sln

script:
- msbuild /p:Configuration=Release USFM_Converter.sln
