version: 1.0.{build}
configuration: Release
before_build:
- cmd: nuget restore USFM_Converter.sln
build_script:
- cmd: 'msbuild USFM_Converter.sln /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /p:Configuration=Release'
after_build:
- cmd: '"C:\Program Files (x86)\Inno Setup 6\iscc.exe" installerscript.iss'
- cmd: mv %APPVEYOR_BUILD_FOLDER%/Output/usfmsetup.exe ./USFM_Converter_Installer.exe
artifacts:
  - path: USFM_Converter_Installer.exe
    name: installer
  
deploy:
- provider: S3
  access_key_id:
    secure: fTolX5IVtC+EMnchVGHM55HR8bmUw0MEkNfDJvcUirE=
  secret_access_key:
    secure: BokZbJlUOWKugyqrxUa+4LGkdNUA2Ydp/59kcxInrdbuiiTEfmvuhw3zOdc5RKAQ
  region: us-east-1
  bucket: nightlybuilds
  folder: $(APPVEYOR_REPO_NAME)/$(APPVEYOR_REPO_BRANCH)/$(APPVEYOR_BUILD_NUMBER)
  artifact: installer
  set_public: true
- provider: GitHub
  auth_token:
    secure: yVVt0QpBtamXBkqn3N4kBxatFqrzmRiG0FG+H3p2dthbrqDnEZ8TlsNY/cAlqErq
  artifact: installer
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true
    
